name: Azure Function App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -t ./function_app/.python_packages/lib/site-packages -r requirements.txt

      - name: Copy .env to function app
        run: cp .env function_app/

      - name: List installed packages
        run: |
          ls -R function_app/.python_packages/lib/site-packages
          python -c "import sys; print(sys.path)"

      - name: Archive function app
        run: zip -r functionapp.zip function_app

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'bahaFunctionApp'
          package: './functionapp.zip'
          publish-profile: '${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
