name: Azure Function App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies in virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy .env to function app
        run: cp .env function_app/

      - name: Package function app with virtual environment
        run: |
          mkdir -p package
          cp -r function_app/* package/
          cp -r venv/lib/python3.10/site-packages/* package/
          cd package
          zip -r ../functionapp.zip .
          cd ..

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'bahaFunctionApp'
          package: './functionapp.zip'
          publish-profile: '${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
